[package]
name = "secure-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
argon2.workspace = true
rand_core.workspace = true
secrecy.workspace = true
serde.workspace = true
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows-dpapi = "=0.2.0"

[target.'cfg(unix)'.dependencies]
keyring = "=4.1.5"
